In [2]:
import numpy as np

# 提取数组属性
ndarray.ndim	数组的秩（rank），即数组的维度数量或轴的数量。  
ndarray.shape	数组的维度，表示数组在每个轴上的大小。对于二维数组（矩阵），表示其行数和列数。  
ndarray.size	数组中元素的总个数，等于 ndarray.shape 中各个轴上大小的乘积。  
ndarray.dtype	数组中元素的数据类型。  
ndarray.itemsize	数组中每个元素的大小，以字节为单位。  
ndarray.flags	包含有关内存布局的信息，如是否为 C 或 Fortran 连续存储，是否为只读等。  
ndarray.real	数组中每个元素的实部（如果元素类型为复数）。  
ndarray.imag	数组中每个元素的虚部（如果元素类型为复数）。  
ndarray.data	实际存储数组元素的缓冲区，一般通过索引访问元素，不直接使用该属性。

In [95]:
elevation_readings = np.array([245, 312, 156, 423, 678])
print(f"1D Array (elevation readings): {elevation_readings}")
print(f"Array rank: {elevation_readings.ndim}")
print(f"Data dtype: {elevation_readings.dtype}")
print(f"Array shape: {elevation_readings.shape}")
print(f"Array size: {elevation_readings.size}")
print(f"Array item size: {elevation_readings.itemsize} bytes")
print(f"Array flags: {elevation_readings.flags}")
print(f"Array real part: {elevation_readings.real}")
print(f"Array imaginary part: {elevation_readings.imag}")
print(f"Array data buffer: {elevation_readings.data}")

1D Array (elevation readings): [245 312 156 423 678]
Array rank: 1
Data dtype: int32
Array shape: (5,)
Array size: 5
Array item size: 4 bytes
Array flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Array real part: [245 312 156 423 678]
Array imaginary part: [0 0 0 0 0]
Array data buffer: <memory at 0x000001E08F9D0B80>


# numpy.zeros
创建指定大小的数组，数组元素以 0 来填充：  
numpy.zeros(shape, dtype = float, order = 'C')  
参数说明：  
shape	数组形状  
dtype	数据类型，可选  
order	'C' 用于 C 的行数组，或者 'F' 用于 FORTRAN 的列数组

In [121]:
distance_matrix = np.zeros((5,5))  # Create a 1D array of zeros with 5 elements
print(f"1D Array (distance matrix): {distance_matrix}")
print(f"Data type: {distance_matrix.dtype}")
print(f"Array shape: {distance_matrix.shape}")
print(f"Array size: {distance_matrix.size}")

1D Array (distance matrix): [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Data type: float64
Array shape: (5, 5)
Array size: 25


# numpy.ones
创建指定形状的数组，数组元素以 1 来填充  
numpy.ones(shape, dtype = None, order = 'C')

In [122]:
ones = np.ones((5,5))  # Create a 1D array of ones with 5 elements
print(f"1D Array (ones): {ones}")

1D Array (ones): [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


numpy.ones()还可以进行运算，来填充不同数字

In [123]:
#fill in any numbers
weights = np.ones((2, 4)) * 0.5 # 填充0.5的数组
print(f"Array of weights (0.5):\n{weights}")
print(weights.dtype,weights.itemsize)  # 输出每个元素的字节大小

Array of weights (0.5):
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
float64 8


# numpy.zeros_like
numpy.zeros_like 用于创建一个与给定数组具有相同形状的数组，数组元素以 0 来填充。  
numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)  
参数说明：  
a	给定要创建相同形状的数组  
dtype	创建的数组的数据类型  
order	数组在内存中的存储顺序，可选值为 'C'（按行优先）或 'F'（按列优先），默认为 'K'（保留输入数组的存储顺序）  
subok	是否允许返回子类，如果为 True，则返回一个子类对象，否则返回一个与 a 数组具有相同数据类型和存储顺序的数组  
shape	创建的数组的形状，如果不指定，则默认为 a 数组的形状。  

In [133]:
# 创建一个 3x3 的二维数组
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# 创建一个与 arr 形状相同的，所有元素都为 0 的数组
zeros_arr = np.zeros_like(arr)
print(zeros_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# numpy.ones_like
numpy.ones_like 用于创建一个与给定数组具有相同形状的数组，数组元素以 1 来填充。

In [143]:
# 创建一个 3x3 的二维数组
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# 创建一个与 arr 形状相同的，所有元素都为 1 的数组
ones_arr = np.ones_like(arr)
print(ones_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# 数组的类型也可以在创建时明确指定

In [144]:
# Create an array for marking valid data points.
c = np.array([[1, 2], [3, 4]], dtype=complex)#complex array
print(f"Complex array:\n{c}")

Complex array:
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [145]:
# Create an array for marking valid data points.
valid_data_flags = np.ones((5,), dtype=bool) # 最初全部为True
print(f"Data validity flags: {valid_data_flags}")

Data validity flags: [ True  True  True  True  True]


# empty 创建一个初始内容是随机的，取决于内存状态的数组。默认情况下，创建的数组的 dtype 是 float64，但可以通过关键字参数 dtype 指定。

In [146]:
empty = np.empty((2, 3))  # 创建一个未初始化的数组
print(f"Empty array:\n{empty}")

Empty array:
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


# arange 函数是一个内置函数，它创建一个具有数字序列的NumPy 数组。
 np.arange()函数分为一个参数，两个参数，三个参数三种情况  
一个参数时，参数值为终点$\color{red}{(不包含)}$，起点取默认值0，步长取默认值1。  
两个参数时，第一个参数为起点，第二个参数为终点，步长取默认值1。  
三个参数时，第一个参数为起点，第二个参数为终点，第三个参数为步长。其中步长支持小数  

In [2]:
# arange 函数是一个内置函数，它创建一个具有数字序列的NumPy 数组。
import numpy as np
#一个参数的情况
single_arg_array = np.arange(5)  # 从0到4
print(f"Single argument arange array: {single_arg_array}")
#两个参数的情况
two_arg_array = np.arange(3, 8)  # 从3到7   
print(f"Two argument arange array: {two_arg_array}")
#三个参数的情况
arange_array = np.arange(2010, 2021, 1) # 从2010到2020，步长为1
print(f"Three argument arange array: {arange_array}")
#或为网格创建纬度值
latitudes = np.arange(-90, 91, 30) # 从-90到90度，每30度
print(f"Latitude grid: {latitudes}")

Single argument arange array: [0 1 2 3 4]
Two argument arange array: [3 4 5 6 7]
Three argument arange array: [2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]
Latitude grid: [-90 -60 -30   0  30  60  90]


# arange以步长为参数，而linspace以元素数量为参数

In [3]:
#使用linspace来获得均匀间隔的值
longitudes = np.linspace(-180, 180, 7) # 从-180到180的7个均匀间隔值
print(f"Longitude grid: {longitudes}")

Longitude grid: [-180. -120.  -60.    0.   60.  120.  180.]


# np.round()用于对数组或单个数值进行四舍五入。该函数返回一个与输入类型相同的数组或数值，并可以通过可选的参数来指定保留的小数位数。
np.round(a, decimals=0, out=None)
参数说明  
a：待进行四舍五入操作的数组或单个数值。  
decimals：可选参数，指定保留的小数位数，默认为0。  
out：可选参数，无需手动指定。  
返回值  
返回与输入类型相同的数组或数值。

In [4]:
locations = np.array([[35.6895, 139.6917], [40.7128, -74.0060], [51.5074, -0.1278]]) # 东京 # 纽约# 伦敦
locations_rounded = np.round(locations, decimals=2) # 保留两位小数
print(f"Original locations:\n{locations}")
print(f"Locations (rounded):\n{locations_rounded}")

Original locations:
[[ 3.568950e+01  1.396917e+02]
 [ 4.071280e+01 -7.400600e+01]
 [ 5.150740e+01 -1.278000e-01]]
Locations (rounded):
[[ 3.5690e+01  1.3969e+02]
 [ 4.0710e+01 -7.4010e+01]
 [ 5.1510e+01 -1.3000e-01]]


# NumPy 最大的优势之一是向量化——能够一次对整个数组执行数学运算，而无需编写显式循环。
## 向量化操作

In [5]:
# 逐元素加法 - 向每个元素添加相同的值
# 示例：通过添加参考高度调整高程读数
elevation_readings = np.array([245, 312, 156, 423, 678])
sea_level_adjustment = elevation_readings + 10 # 向所有读数添加10米
print(f"Original elevations: {elevation_readings}")
print(f"Adjusted elevations: {sea_level_adjustment}")
#逐元素乘法 - 将每个元素乘以相同的值
# 示例：将高程从米转换为英尺（1米 = 3.28084英尺）
elevations_meters = np.array([245, 312, 156, 423, 678])
elevations_feet = elevations_meters * 3.28084
print(f"Elevations in meters: {elevations_meters}")
print(f"Elevations in feet: {elevations_feet.round(1)}") # 四舍五入到1位小数
# 您也可以对数组进行加、减和除运算
temperatures_celsius = np.array([15.5, 22.3, 8.9, 31.2])
temperatures_fahrenheit = temperatures_celsius * 9 / 5 + 32
print(f"Temperatures in Celsius: {temperatures_celsius}")
print(f"Temperatures in Fahrenheit: {temperatures_fahrenheit.round(1)}")

Original elevations: [245 312 156 423 678]
Adjusted elevations: [255 322 166 433 688]
Elevations in meters: [245 312 156 423 678]
Elevations in feet: [ 803.8 1023.6  511.8 1387.8 2224.4]
Temperatures in Celsius: [15.5 22.3  8.9 31.2]
Temperatures in Fahrenheit: [59.9 72.1 48.  88.2]


# 向量化操作也可以在不同NumPy 数组之间执行

In [6]:
# 数组之间的操作 - 两个数组之间的逐元素操作
# 示例：计算加权坐标
coordinates = np.array(
[[35.6895, 139.6917], [40.7128, -74.0060], [51.5074, -0.1278]] )# 东京 # 纽约# 伦敦
# 对纬度和经度应用不同的权重（对某些投影有用）
weights = np.array([1.0, 0.8]) # 正常加权纬度，减少经度权重
weighted_coords = coordinates * weights
print(f"Original coordinates:\n{coordinates}")
print(f"Weighted coordinates:\n{weighted_coords}")
# 您也可以在相同形状的数组之间执行操作
coord_differences = coordinates - coordinates[0] # 与第一个城市（东京）的距离
print(f"Coordinate differences from Tokyo:\n{coord_differences}")

Original coordinates:
[[ 3.568950e+01  1.396917e+02]
 [ 4.071280e+01 -7.400600e+01]
 [ 5.150740e+01 -1.278000e-01]]
Weighted coordinates:
[[ 3.5689500e+01  1.1175336e+02]
 [ 4.0712800e+01 -5.9204800e+01]
 [ 5.1507400e+01 -1.0224000e-01]]
Coordinate differences from Tokyo:
[[   0.        0.    ]
 [   5.0233 -213.6977]
 [  15.8179 -139.8195]]


## 某些操作，例如 += 和 *=，会就地修改现有数组，而不是创建新数组。

In [7]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
print(f"Array a after multiplication:\n{a}")
print(f"Array b (random values):\n{b}")
b += a
print(f"Array b after addition with a:\n{b}")
a += b  # b is not automatically converted to integer type

Array a after multiplication:
[[3 3 3]
 [3 3 3]]
Array b (random values):
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
Array b after addition with a:
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

# 重塑数组
## numpy.reshape()用于改变数组的形状而不改变其数据
reshape函数允许我们改变数组的维度，而不改变其数据。这个函数的基本语法如下：  
numpy.reshape(a, newshape, order='C')  
其中：  
– a是要重塑的数组  
– newshape是一个整数或者整数元组，指定新的形状  
– order参数决定元素的读取顺序，默认为’C’（按行优先）

In [ ]:
# 创建一个一维数组
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array from numpyarray.com:")
print(arr)

# 将一维数组重塑为2x3的二维数组
reshaped_arr = arr.reshape(2, 3)
print("Reshaped array from numpyarray.com:")
print(reshaped_arr)

Original array from numpyarray.com:
[1 2 3 4 5 6]
Reshaped array from numpyarray.com:
[[1 2 3]
 [4 5 6]]


##  使用-1作为维度参数
reshape函数的一个非常有用的特性是可以使用-1作为维度参数。  
当使用-1时，NumPy会自动计算这个维度的大小，以确保数组包含原始数据中的所有元素。

In [ ]:
# 创建一个12元素的一维数组
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original array from numpyarray.com:")
print(arr)

# 使用-1自动计算一个维度
reshaped_arr = arr.reshape(3, -1)
print("Reshaped array from numpyarray.com:")
print(reshaped_arr)

Original array from numpyarray.com:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array from numpyarray.com:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 多维数组的reshape
reshape函数不仅可以用于一维数组，还可以用于多维数组。我们可以将高维数组重塑为低维数组，或者将低维数组重塑为高维数组。

In [ ]:
# 创建一个2x6的二维数组
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12]])
print("Original array from numpyarray.com:")
print(arr)

# 将2x6的数组重塑为2x2x3的三维数组
reshaped_arr = arr.reshape(2, 2, 3)
print("Reshaped array from numpyarray.com:")
print(reshaped_arr)

Original array from numpyarray.com:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshaped array from numpyarray.com:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 使用元组指定新形状
除了直接传递多个整数参数，我们还可以使用元组来指定新的形状。这在处理动态形状或者从变量中读取形状时特别有用。

In [ ]:
# 创建一个24元素的一维数组
arr = np.arange(1, 25)
print("Original array from numpyarray.com:")
print(arr)

# 使用元组指定新形状
new_shape = (2, 3, 4)
reshaped_arr = arr.reshape(new_shape)
print("Reshaped array from numpyarray.com:")
print(reshaped_arr)

Original array from numpyarray.com:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Reshaped array from numpyarray.com:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


# 展平多维数组
reshape函数还可以用来”展平”多维数组，即将多维数组转换为一维数组。这在数据预处理和特征工程中经常用到。
## 注意numpy.reshape(-1)返回一个1 维数组（秩为 1）
## 而numpy.reshape((1,-1)))返回一个2维数组（秩为 2）

In [ ]:
# 创建一个2x3x4的三维数组
arr = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]],
                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
print("Original array from numpyarray.com:")
print(arr)

# 将三维数组展平为一维数组
flattened_arr = arr.reshape(-1)
print("Flattened array from numpyarray.com:")
print(flattened_arr)
# 将三维数组展平为一行的二维数组
flattened_arr2 = arr.reshape((1,-1))
print("Flattened array from numpyarray.com:")
print(flattened_arr2)

Original array from numpyarray.com:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Flattened array from numpyarray.com:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Flattened array from numpyarray.com:
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]


## 使用reshape创建列向量和行向量

In [ ]:
# 创建一个一维数组
arr = np.array([1, 2, 3, 4, 5])
print("Original array from numpyarray.com:")
print(arr)

# 创建列向量
column_vector = arr.reshape(-1, 1)
print("Column vector from numpyarray.com:")
print(column_vector)

# 创建行向量
row_vector = arr.reshape(1, -1)
print("Row vector from numpyarray.com:")
print(row_vector)

Original array from numpyarray.com:
[1 2 3 4 5]
Column vector from numpyarray.com:
[[1]
 [2]
 [3]
 [4]
 [5]]
Row vector from numpyarray.com:
[[1 2 3 4 5]]


# 数组扁平化
## numpy.flatten(order='C')  
将数组的副本（不更改原始数据）转换为一维，简单理解就是把数组拉平拉直  
options order={'C', 'F', 'A', 'K'}  

'C': C-style, 行为主要顺序，先从左到右，再从上到下,默认是**'C'**  
'F': Fortran-style, 列为主要顺序，先从上到下，再从左到右  
'A'：如果a是Fortran在内存中连续的，那么'A' 意味着以列主要顺序变平，否则按行排序  
'F'：按照元素在内存中出现的顺序来拉平a

In [ ]:
# 随机生成一个2维数组，4行3列
arr1 = np.random.randint(1, 10, size=[4, 3])
# 将数组arr1以行为主要顺序进行拉平降维
arr2 = arr1.flatten()
# 将数组arr1以列为主要顺序进行拉平降维
arr3 = arr1.flatten(order='F')
print(f"Original array (arr1):\n{arr1}")
print(f"Flattened array (row-major, arr2):\n{arr2}")    
print(f"Flattened array (column-major, arr3):\n{arr3}") 

Original array (arr1):
[[9 5 2]
 [6 2 5]
 [2 2 9]
 [5 2 5]]
Flattened array (row-major, arr2):
[9 5 2 6 2 5 2 2 9 5 2 5]
Flattened array (column-major, arr3):
[9 6 2 5 5 2 2 2 2 5 9 5]


# NumPy 数组中的乘法运算符 * 是逐元素操作的。***矩阵乘法***可以使用 @ 运算符或 arrat=y.dot(array) 函数或方法执行


In [ ]:
# 向量化操作也可以在不同NumPy 数组之间执行
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product
print(f"Elementwise product of A and B:\n{A * B}")
A @ B     # matrix product
print(f"Matrix product of A and B:\n{A @ B}")
A.dot(B)  # another matrix product
print(f"Matrix product of A and B using dot:\n{A.dot(B)}")

Elementwise product of A and B:
[[2 0]
 [0 4]]
Matrix product of A and B:
[[5 4]
 [3 4]]
Matrix product of A and B using dot:
[[5 4]
 [3 4]]


# 数组上的数学函数
NumPy 提供了一个全面的数学函数库，对数组进行逐元素操作

## 角度和弧度转换
转为角度：np.degrees()或者np.rad2deg()  
角度 = 弧度 × (180 / π)  
转为弧度:np.radians()或者np.deg2rad()  
公式：弧度 = 角度 × (π / 180)

In [ ]:
import numpy as np
import sympy as sp  # 导入符号计算库
##deg2rad
# 单个角度值转换（90度对应π/2弧度）
deg = 90
rad = np.radians(deg)  # 或 np.deg2rad(deg)
print(rad)  # 输出：1.5707963267948966（约等于π/2）

# 数组转换
degrees = np.array([0, 30, 45, 60, 90])
radians = np.radians(degrees)
print(radians)  

##rad2deg
# 单个弧度值转换（π弧度对应180度）
rad = np.pi
deg = np.degrees(rad)  # 或 np.rad2deg(rad)
print(deg)  # 输出：180.0

# 数组转换
radians = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
degrees = np.degrees(radians)
print(degrees)  

1.57079632679490
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
180.0
[ 0. 30. 45. 60. 90.]


In [ ]:
#注：如果想输出pi/圆周率，可以使用sympy的sp.rad方法
# 示例：将角度转换为弧度
angle = 180
radian = sp.rad(angle)
print(f"Angle in radians: {radian}")  # 输出：π弧度

# 示例：将角度数组转换为弧度数组
angle_array = np.array([0, 30, 45, 60, 90])
radian_array = sp.rad(angle_array)
print(f"Angle array in radians: {radian_array}")  # 输出符号数组

Angle in radians: pi
Angle array in radians: [0 pi/6 pi/4 pi/3 pi/2]


## 三角函数
sin(x, /[, out, where, casting, order, ...])

三角正弦，逐元素计算。

cos(x, /[, out, where, casting, order, ...])

逐元素余弦。

tan(x, /[, out, where, casting, order, ...])

逐元素计算正切。

arcsin(x, /[, out, where, casting, order, ...])

反正弦，逐元素计算。

asin(x, /[, out, where, casting, order, ...])

反正弦，逐元素计算。

arccos(x, /[, out, where, casting, order, ...])

三角反余弦，逐元素计算。

acos(x, /[, out, where, casting, order, ...])

三角反余弦，逐元素计算。

arctan(x, /[, out, where, casting, order, ...])

三角反正切，逐元素计算。

atan(x, /[, out, where, casting, order, ...])

三角反正切，逐元素计算。

hypot(x1, x2, /[, out, where, casting, ...])

给定直角三角形的“直角边”，返回其斜边。

arctan2(x1, x2, /[, out, where, casting, ...])

逐元素计算 x1/x2 的反正切，并正确选择象限。

atan2(x1, x2, /[, out, where, casting, ...])

逐元素计算 x1/x2 的反正切，并正确选择象限。

degrees(x, /[, out, where, casting, order, ...])

将角度从弧度转换为度数。

radians(x, /[, out, where, casting, order, ...])

将角度从度数转换为弧度。

unwrap(p[, discont, axis, period])

通过计算与周期相关的大增量的补码来解卷绕。

deg2rad(x, /[, out, where, casting, order, ...])

将角度从度数转换为弧度。

rad2deg(x, /[, out, where, casting, order, ...])

将角度从弧度转换为度数。

In [14]:
#三角函数 - 坐标转换的基础
131
angles_degrees = np.array([0, 30, 45, 60, 90])
angles_radians = np.radians(angles_degrees) # 首先转换为弧度
sine_values = np.sin(angles_radians)
cosine_values = np.cos(angles_radians)
print(f"Angles (degrees): {angles_degrees}")
print(f"Sine values: {sine_values.round(3)}")
print(f"Cosine values: {cosine_values.round(3)}")

Angles (degrees): [ 0 30 45 60 90]
Sine values: [0.    0.5   0.707 0.866 1.   ]
Cosine values: [1.    0.866 0.707 0.5   0.   ]


# 对数和指数函数
exp(x, /[, out, where, casting, order, ...])

计算输入数组中所有元素的指数。

expm1(x, /[, out, where, casting, order, ...])

计算数组中所有元素的 exp(x) - 1。

exp2(x, /[, out, where, casting, order, ...])

计算输入数组中所有 p 的 2**p。

log(x, /[, out, where, casting, order, ...])

自然对数，逐元素计算。

log10(x, /[, out, where, casting, order, ...])

逐元素返回输入数组的以 10 为底的对数。

log2(x, /[, out, where, casting, order, ...])

以 2 为底的 x 的对数。

log1p(x, /[, out, where, casting, order, ...])

逐元素返回输入数组加一的自然对数。

logaddexp(x1, x2, /[, out, where, casting, ...])

输入指数和的对数。

logaddexp2(x1, x2, /[, out, where, casting, ...])

以 2 为底的输入指数和的对数。



In [15]:
# 对数和指数函数
population_data = np.array([100000, 500000, 1000000, 5000000, 10000000])
# 对数变换通常用于标准化高度偏斜的数据，如人口
log_population = np.log10(population_data) # 以10为底的对数
print(f"Population data: {population_data}")
print(f"Log10 of population: {log_population.round(2)}")
# 指数函数
growth_rates = np.array([0.01, 0.02, 0.03, 0.05]) # 1%, 2%, 3%, 5%增长率
exponential_growth = np.exp(growth_rates) # e^x
print(f"Growth rates: {growth_rates}")
print(f"Exponential factors: {exponential_growth.round(3)}")

Population data: [  100000   500000  1000000  5000000 10000000]
Log10 of population: [5.  5.7 6.  6.7 7. ]
Growth rates: [0.01 0.02 0.03 0.05]
Exponential factors: [1.01  1.02  1.03  1.051]


# 统计操作
统计分析是理解地理空间数据的基础。NumPy 提供高效的函数来计算描述性统计，帮助您理解数据的特征：集中趋势（均值、中位数）、变异性（标准差、方差）和分布（最小值、最大值、百分位数）。
maximum(x1, x2, /[, out, where, casting, ...])保留 NaN

逐元素计算两个数组元素的最大值。

fmax(x1, x2, /[, out, where, casting, ...])忽略 NaN

逐元素计算两个数组元素的最大值。

max(a[, axis, out, keepdims, initial, where])默认不会忽略 NaN

返回数组的最大值或沿轴的最大值。

nanmax(a[, axis, out, keepdims, initial, where])忽略 NaN

返回数组的最大值或沿轴的最大值，忽略任何非数字 (NaNs)。

minimum(x1, x2, /[, out, where, casting, ...])保留nan

逐元素计算两个数组元素的最小值。

fmin(x1, x2, /[, out, where, casting, ...])忽略nan

逐元素计算数组元素的最小值。

min(a[, axis, out, keepdims, initial, where])保留nan

返回数组的最小值或沿轴的最小值。

nanmin(a[, axis, out, keepdims, initial, where])忽略nan

返回数组的最小值或沿轴的最小值，忽略任何非数字 (NaNs)。

## 集中趋势
|函数|功能|忽略 NaN 的版本|
|:----:|:----:|:----:|
np.mean(a)	|计算算术平均值（默认不忽略 NaN）|	np.nanmean(a)
np.median(a)	|计算中位数（默认不忽略 NaN）	|np.nanmedian(a)
np.average(a)	|计算加权平均值（可指定权重）	|无（需手动处理）

## 离散程度（数据分散性）
函数	|功能|	忽略 NaN 的版本
|:----:|:----:|:----:|
np.var(a)	|计算方差（默认总体方差，ddof=0）|	np.nanvar(a)
np.std(a)	|计算标准差（方差的平方根）	|np.nanstd(a)
np.ptp(a)	|计算极差（最大值 - 最小值）|	无（需结合 nanmax/nanmin）

In [19]:
elevation_profile = np.array(
[1245, 1367, 1423, 1389, 1456, 1502, 1478, 1398, 1334, 1278,np.nan]
)
# 基本描述性统计
mean_elevation = np.nanmean(elevation_profile)
median_elevation = np.nanmedian(elevation_profile)
std_elevation = np.nanstd(elevation_profile)
min_elevation = np.nanmin(elevation_profile)
max_elevation = np.nanmax(elevation_profile)
print(f"Elevation Profile Statistics:")
print(f"Mean elevation: {mean_elevation:.1f} meters")
print(f"Median elevation: {median_elevation:.1f} meters")
print(f"Standard deviation: {std_elevation:.1f} meters")
print(f"Elevation range: {min_elevation} - {max_elevation} meters")

Elevation Profile Statistics:
Mean elevation: 1387.0 meters
Median elevation: 1393.5 meters
Standard deviation: 79.3 meters
Elevation range: 1245.0 - 1502.0 meters
